### ISSUE TITLE
Chess bug

### ISSUE THREAD

**Issue by ratan3577** [Geras1mleo/Chess#14]
**Describe the bug**
Castling move is not shown properly in ExecutedMoves. It is applicable in both short castling and long castling. Instead of e8g8, it is showing e8h8 for black short castling. Same way instead of White long castling it is showing e1a1 instead of e1c1.  
Conversions / Validations / ...

**To Reproduce**
Steps to reproduce the behaviour or
Eventually a call stack and input data

            string str = "1. e4 c5 2. Nf3 d6 3. Nc3 Nc6 4. Bb5 Nf6 5. d3 a6 6. Bxc6+ bxc6 7. Bg5 g6 8. Qd2 Bg7 9. Bh6 O-O 10. Bxg7 Kxg7 11. O-O-O Rb8 12. Ng5 Qb6 13. Na4 Qb5 14. b3 d5 15. e5 Nd7 16. e6 Nf6 17. exf7 h6 18. Nf3 Be6 19. Ne5 Bxf7 20. Nxf7 Rxf7 21. f3 c4 22. dxc4 dxc4 23. Qc3 cxb3 24. axb3 Qg5+ 25. Kb1 e6 26. Nc5 Kg8 27. g4 Rb5 28. Rd8+ Rf8 29. Rxf8+ Kxf8 30. Nxe6+ Kf7 31. Nxg5+ 1-0";

var board = new ChessBoard();
board = ChessBoard.LoadFromPgn(str);
 foreach(var move in board.ExecutedMoves)
            {

//Check 9th move of black and 11th move of white. Instead of e8g8, it is showing e8h8 for black short castling. Same way instead of White long castling it is showing e1a1 instead of e1c1. King would not move to extreme corner after castling.

}

**Expected behaviour**

Black short castling = e8g8
White long castle = e1c1

same way,
Black long castling = e8c8
White short castle = e1g1

**Screenshots**

**Additional context**

**Comment by Geras1mleo** [comment]
I will make it optional behavior.
Thank you for your feedback

**Comment by zakkoo** [comment]
Hi Geras

That sounds great. Thank you for your wonderful project. I'm building an app based on it and I love it. Keep up the good work.

Best regards,
Chess fan
